name: brn-web3-type-converter

myWebsite:
  component: "@serverless/website"
  inputs:
    code:
      root: ./
      src: ./src
      hook: echo "Done"
    region: us-east-1
    domain: web3-type-converter.onbrn.com
